### ISSUE TITLE
GTM/GA: audio player tracking

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1077]
AC:
- [x] Sends audio player events to NPR's GA, specifically
  - [x] Live stream: play, pause, change
  - [x] Inline audio: play, pause
  ~~- [ ] On demand audio: play, pause~~

**Comment by arellaTV** [comment]
There isn't really a means to play on-demand audio (podcasts) on our site, so @patrickdougall and I have decided to label web audio as "Inline"

**Comment by arellaTV** [comment]
Merged!
