### ISSUE TITLE
LAist: Restore Author meta tag

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1300]
AC:

- [ ] There is an author meta tag (probably `article:author`)
- [ ] The tag is fed into Chartbeat (originally was `vr:author`, but that tag's been deprecated)

**Comment by arellaTV** [comment]
- [ ] Also restore category meta tag (probably article:category)
