### ISSUE TITLE
The Big One: Add social meta tags and GTM container to header

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1335]
AC:

- [x] There are social meta tags for facebook and twitter
- [x] There is a GTM script in the head, and iframe in the body
- [x] The social buttons in the summary open up share windows

**Comment by jo-im** [comment]
Jay has already added social meta tags for Facebook and Twitter and make the social buttons in the summary open up share windows. His changes are pushed to master and his commit that holds these changes are here:
https://github.com/SCPR/the-big-one/commit/93558736862a776a5eefdf75bd922befef14d5fb

I have added the GTM script in the head and iframe in the body and pushed it to master. The commit that holds these changes are here:
https://github.com/SCPR/the-big-one/commit/01cb2a1978f051f09a54a76c6fec61bc82786e81
