### ISSUE TITLE
Additional Homepage Event Tracking

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#429]
AC

- [ ] Track scroll depth
- [ ] How many clicks for stories relative to scroll depth
- [ ] Total clickthroughs to news stories

**Comment by Ravenstine** [comment]
Scroll events confirmed live in GA.
