### ISSUE TITLE
Implement a Bounce Catcher for Newsletters and Donation Asks

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#784]
AC

- [ ] There is an agreed upon understanding of what it means when a user is likely "bouncing" (ex. Their mouse moves to the top and left 15% of the browser window on desktop, or they scroll up at a rate of X on mobile)

- [ ] There is an easy way to make sure the ask is as relevant as possible (ex. shows get show specific asks, everything else gets the short list, and during drives we can override with a donation ask)

- [ ] There are controls for a non-developer to change the language of the asks

- [ ] The modal / pop-up is easily dismissable

**Comment by vsinghkpcc** [comment]
Issue moved to [SCPR/digital_products #176](https://github.com/SCPR/digital_products/issues/176) via [**ZenHub**](https://www.zenhub.com/)
