### ISSUE TITLE
Aesthetic Unity: Verify GA tracking for all links

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#855]
AC:

~~- [ ] Every cell with `<a>` tags have a `data-ga-category`, `data-ga-action`, and `data-ga-label`~~
- [x] Most cells with `<a>` tags mirror SCPR production with appropriate `data-ga-category`, `data-ga-action`, and `data-ga-label` attrributes. (Only Blog Posts are missing, pulled to a new ticket)
- [x] GA helpers are running on every page (verify on GA)

**Comment by arellaTV** [comment]
Underestimated the point value of this ticket. Is more like a 2-3 point ticket. Will split off if needed!

**Comment by arellaTV** [comment]
GA Links Verified:
- [ ] Homepage, r
- [ ] Article https://github.com/SCPR/design/issues/211, r
- [ ] Show Segment, r
- [ ] Blog Post, r
- [ ] Full-width (e.g. membership) https://github.com/SCPR/design/issues/214, nr
- [ ] Full width special (e.g. about) https://github.com/SCPR/design/issues/214, nr
- [ ] Podcasts https://github.com/SCPR/design/issues/212, nr
- [ ] Vertical Landing, https://github.com/SCPR/design/issues/203 nr
- [ ] Show Landing, https://github.com/SCPR/design/issues/203 nr
- [ ] Blog Landing, https://github.com/SCPR/design/issues/203 nr
- [ ] In Person Landing https://github.com/SCPR/design/issues/213, nr
- [ ] Events List https://github.com/SCPR/design/issues/213, nr
- [ ] Individual Event https://github.com/SCPR/design/issues/213, nr
- [ ] Show landing, https://github.com/SCPR/design/issues/203, r
- [ ] Program List https://github.com/SCPR/design/issues/212
- [ ] Schedule https://github.com/SCPR/design/issues/212
- [ ] Episode Landing Page https://github.com/SCPR/design/issues/226
- [ ] Listen Live https://github.com/SCPR/design/issues/215
- [ ] Short List https://github.com/SCPR/design/issues/216
- [ ] Latest News https://github.com/SCPR/design/issues/204
- [ ] Archive https://github.com/SCPR/design/issues/204
- [ ] Search Results https://github.com/SCPR/design/issues/204

**Comment by arellaTV** [comment]
GA tracking progress here:
https://docs.google.com/spreadsheets/d/1pMjSDhXBcv04VByOAHL2r1FyjUvEvGR3Z0EbTJ1T_58/edit#gid=0

Will first collect everything that is missing, and then address them afterwards for two reasons:
1. A lot of missing GA elements are shared between pages like the play and pause buttons and listen live menu button
2. It will be easier to group together elements and optimize for time

GA Links Added to Report
- [x] Article https://github.com/SCPR/design/issues/211, r
- [ ] Show Segment, r
- [ ] Blog Post, r
- [ ] Full-width (e.g. membership) https://github.com/SCPR/design/issues/214, nr
- [ ] Full width special (e.g. about) https://github.com/SCPR/design/issues/214, nr
- [ ] Podcasts https://github.com/SCPR/design/issues/212, nr
- [ ] Vertical Landing, https://github.com/SCPR/design/issues/203 nr
- [ ] Show Landing, https://github.com/SCPR/design/issues/203 nr
- [ ] Blog Landing, https://github.com/SCPR/design/issues/203 nr
- [ ] In Person Landing https://github.com/SCPR/design/issues/213, nr
- [ ] Events List https://github.com/SCPR/design/issues/213, nr
- [ ] Individual Event https://github.com/SCPR/design/issues/213, nr
- [ ] Show landing, https://github.com/SCPR/design/issues/203, r
- [ ] Program List https://github.com/SCPR/design/issues/212
- [ ] Schedule https://github.com/SCPR/design/issues/212
- [ ] Episode Landing Page https://github.com/SCPR/design/issues/226
- [ ] Listen Live https://github.com/SCPR/design/issues/215
- [ ] Short List https://github.com/SCPR/design/issues/216
- [ ] Latest News https://github.com/SCPR/design/issues/204
- [ ] Archive https://github.com/SCPR/design/issues/204
- [ ] Search Results https://github.com/SCPR/design/issues/204

**Comment by arellaTV** [comment]
GA Links missing:

- [ ] button.jp-play.track-event, button.jp-pause.track-event
  - in all pages
  - resolving this will knock out singlehandedly knock out 13 out of the 20 pages

**Comment by arellaTV** [comment]
Blog post GA event tracking and missing cells will be abstracted to a new ticket: https://github.com/SCPR/SCPRv4/issues/877
